# Yum
- name: Yum
  block:
    - name: Add epel
      yum:
        name: epel-release
        update_cache: yes

    - name: Install Software
      yum: 
        name: "{{ tomcat_packages }}"
        state: present
        update_cache: yes